/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  setupFilesAfterEach: [],
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
};
